name: PyLint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        $HOME/.local/bin/poetry install
    - name: Analysing the code with pylint
      run: |
        $HOME/.local/bin/poetry run pylint --fail-under=8 **/*.py
